### ISSUE TITLE
Intégration du script dans le projet RSSbridge

### ISSUE THREAD

**Issue by propositionjoe** [Guisch/YGG-rss-feed-generator#1]
Salut,
Merci pour le partage, je pense que cela risque d’être utile à pas mal de monde ;)
Je ne sais pas dans quelle mesure cela serait possible de le faire, mais je crois très pertinent d'intégrer ton générateur rss au projet https://github.com/RSS-Bridge/rss-bridge.
On y trouve déjà piratebay, cpasbien, eztv... parce que la dispersion c’est toujours dommage.

**Comment by Guisch** [comment]
Salut,

je ne connaissait pas rss-bridge, merci de me l'avoir fait découvrir.
Cependant, d'après les bridges que j'ai vu, les liens dans le flux rss redirige vers la page de présentation du torrent. Le but est donc différent de YGG rss feed generator, qui lui donne des liens direct pour le téléchargement du fichier .torrent.

**Comment by propositionjoe** [comment]
Très juste.
À bientôt
