### ISSUE TITLE
Dernière modif

### ISSUE THREAD

**Issue by exrat** [Guisch/YGG-rss-feed-generator#10]
Salut
Je viens de tester avec le commit d'hier, ça passe pas chez moi
`[29.03.2018 13:28:38] Erreur lors du chargement du .torrent. (http://yggrss.xxx.xxx//dl.php?action=download&idt=209991)`

Le flux charge bien quand je vais en direct dessus, il bloque sur des torrents qui match et qui sont déjà en seed.
J'ai rien vu de bizarre dans les log nginx qui pourrait aider.
Ex.

**Comment by Guisch** [comment]
Salut !
//dl.php?action=download&idt=209991

Tu peux me dire si le lien sans le double slash avant dl.php fonctionne ?

**Comment by exrat** [comment]
Alors sauf erreur, ça ne marche pas. J'avais tenté de corriger rss.php ligne 49 comme ça
`$rssFeed .= '<link>'. $parent_url . 'dl.php?action=download&idt=' . $torrent['idt'] . '</link>';`
Et même problème avec un seul **/**
Ça plante en rafale sur les +/- 20/25 torrents qui match (cat sport et principalement /gps/carte, des upload à moi)

**Comment by exrat** [comment]
Si tu veux regarder en live, y'a pas de soucis, ce serait peut-être plus simple pour toi ;)
Si tu veux, tu balances un mail xx@xx.xx et je te file la main, tu regardes ça tranquille comme ça...
" Même pas peur ^^ "

**Comment by Guisch** [comment]
https://github.com/Guisch/YGG-rss-feed-generator/commit/0242cd5ba1eee51d12ff1a8de78f3aca6cca9972

Ca devrait fonctionner avec le dernier commit. Tu peux vérifier stp ?

**Comment by exrat** [comment]
C'est ok, c'est bien rentré dans l'ordre. Je te remercie :)
Ex.
