### ISSUE TITLE
Encodage caractères spéciaux

### ISSUE THREAD

**Issue by kgaut** [Guisch/YGG-rss-feed-generator#2]
En sortant un flux et le plaçant dans feedly par exemple, j'ai un soucis avec les caractères spéciaux (accentués principalement) 

![2017-11-09-07-36-33-screenshot-01](https://user-images.githubusercontent.com/736910/32591733-e487958e-c520-11e7-8eb1-1f63171c0a4d.jpg)

Pas le temps de creuser tout de suite, mais je regarderai ça à l'occasion.

**Comment by Guisch** [comment]
Effectivement, j'ai changé pour de l'UTF-8, ça devrait marcher maintenant ;)
