### ISSUE TITLE
Erreur 500

### ISSUE THREAD

**Issue by valounours** [Guisch/YGG-rss-feed-generator#3]
Bonjour,

Je souhaite utiliser ton projet pour ma seedbox mais impossible...

J'ai bien tout fais. (Login et Mdp etc...)

Mais j'obtiens une erreur 500...

Une idée ?

Merci d'avance

**Comment by Guisch** [comment]
Tu peux me passer tes logs apache/nginx stp ?

**Comment by valounours** [comment]
[access.log](https://github.com/Guisch/YGG-rss-feed-generator/files/1487681/access.log)
[error.log](https://github.com/Guisch/YGG-rss-feed-generator/files/1487682/error.log)

Et voila :)

**Comment by Guisch** [comment]
Installe php-curl ou php5-curl selon ta version. N'oublie pas de redémarrer Apache et ça devrait marcher.

**Edit:** J'ai supprimé ton commentaire comportant tes logs car il y avait des données sensibles

**Comment by valounours** [comment]
Je viens d'installer php5-curl (J'ai PHP 5.6.30-0+deb8u1) mais aucun changement toujours l'erreur 500..

**Comment by Guisch** [comment]
Ré-envoie moi ton error.log (fais un `grep ygg error.log` juste pour sortir les erreurs concernées).

**Comment by valounours** [comment]
Et voila : 

_hidden for safety_

**Comment by Guisch** [comment]
Est tu sûr d'avoir bien mis le bon login/mdp dans Ygg.php ligne 93/94 ?

**Comment by valounours** [comment]
Oui, Je viens de revérifier en me connectant sur le site...

Je comprends pas trop la...

**Comment by Guisch** [comment]
Ton login ou ton mot de passe contient-il des caractères spéciaux ? Si oui est-ce qu'il y a l'un des suivants: \x00, \n, \r, \, ', ", \x1a.

**Comment by valounours** [comment]
Non que des chiffres et lettres (majuscules et minuscules)

**Comment by Guisch** [comment]
Peut être un problème de permissions pour le fichier cookie.
Essaye ceci:
```cd /var/www/html/ && sudo chown -R www-data:www-data yggrss```

**Comment by valounours** [comment]
Nickel ça fonctionne mieux ;)

Merci beaucoup :)
