### ISSUE TITLE
Chargement incomplet dans rutorrent

### ISSUE THREAD

**Issue by exrat** [Guisch/YGG-rss-feed-generator#5]
Salut
Merci pour les dernières rectif', il est indispensable ton script ! ;)

J'ai un truc bizarre dans ruTorrent, quand ça match sur quelque chose,  le chargement s’arrête sans prendre les 25 derniers trucs
Un exemple en capture pour que tu vois bien le truc: http://www.ratbox.nl/ext/rss.png

Le flux sur "category=gps&subcategory=cartes" qui match sur la carte tomtom et s’arrête là alors qu'avant il envoyait toujours les 25 résultats.
(le fait que le torrent soit à l’arrêt est normal, c'est juste pour surveiller  les cartes qui tombent...)

Le deuxième sur "category=filmvideo&subcategory=sport" qui ne repère rien charge comme il faut les 25.
Je pense qu'il y a encore un petit bug caché :D 
Ex.

**Comment by Guisch** [comment]
C'est corrigé normalement

**Comment by exrat** [comment]
Super, ça fonctionne. Merci :)
Ex.
